[build-system]
requires = [
    "setuptools==58.0.4",
    "setuptools-rust==1.1.2",
    "setuptools-scm[toml]==6.4.2",
    "wheel==0.37.0",
]

[tool.setuptools_scm]
write_to = "q5/_version.py"
local_scheme = "dirty-tag"
